[package]
name = "dummy_crate"
version = "0.1.0"
edition = "2024"

[dependencies]
backoff = "0.4.0"
rsa = "0.9.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
